### ISSUE TITLE
Search for countries 

### ISSUE THREAD

**Issue by 0xifarouk** [alfianlosari/CoronaVirusTrackerSwiftUI#2]
Adding a search bar to search for country names in Stats tab would be useful.

**Comment by SagarSDagdu** [comment]
@alfianlosari I have added a search bar for searching countries in my pull request( #4 ) to address this issue by @FaroukZeino . 
Please have a look

**Comment by alfianlosari** [comment]
Closing this. Merged @SagarSDagdu  commit with search country included.
